data:
  raw_path: data/raw/liver_cirrhosis.csv
  processed_path: data/processed/processed_data.csv

model:
  type: "XGBoost"
  params:
    n_estimators: 200
    learning_rate: 0.1
    random_state: 42
    objective: "multi:softmax"
    num_class: 3
    eval_metric: "mlogloss"

split:
  test_size: 0.2
  random_state: 42
